apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dopdoc-postgres
  namespace: dopdocai
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: "13.4.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1h
  values:
    image:
      tag: "16"
    auth:
      username: dopdoc
      password: dopdoc
      database: postgres
    primary:
      initdb:
        scripts:
          01-create-multiple-dbs.sql: |
            CREATE DATABASE auth_db;
            CREATE DATABASE dopdoc;
          02-auth-db.sql: |
            -- ============================
            -- Auth Service (minimal)
            -- ============================
            \connect auth_db

            BEGIN;

            -- Пользователи
            CREATE TABLE users (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  -- Уникальный идентификатор пользователя
                email TEXT UNIQUE,                                       -- Email (опционально)
                password_hash TEXT NOT NULL,                             -- Хэш пароля
                is_active BOOLEAN NOT NULL DEFAULT true,                 -- Активен ли аккаунт
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),             -- Дата регистрации
                last_login_at TIMESTAMP                                  -- Последний логин
            );

            -- Refresh-токены (сессии)
            CREATE TABLE refresh_tokens (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  -- ID токена/сессии
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- Владелец
                token_hash TEXT NOT NULL UNIQUE,                         -- Хэш refresh-токена (НЕ сам токен)
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),             -- Когда выдан
                expires_at TIMESTAMP NOT NULL,                           -- Когда истекает
                revoked_at TIMESTAMP,                                    -- Когда отозван (NULL = активен)
                user_agent TEXT,                                         -- User-Agent (опционально)
                ip INET,                                                 -- IP (опционально)

                CONSTRAINT refresh_tokens_exp_chk CHECK (expires_at > created_at)
            );

            -- Индексы
            CREATE INDEX idx_refresh_tokens_user_id
                ON refresh_tokens(user_id);

            CREATE INDEX idx_refresh_tokens_user_created
                ON refresh_tokens(user_id, created_at DESC);

            CREATE INDEX idx_refresh_tokens_not_revoked
                ON refresh_tokens(user_id)
                WHERE revoked_at IS NULL;

            CREATE INDEX idx_refresh_tokens_expires_at
                ON refresh_tokens(expires_at);

            COMMIT;
      persistence:
        enabled: true
        size: 5Gi
        storageClass: longhorn