apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dopdoc-postgres
  namespace: dopdocai
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: "13.4.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1h
  values:
    # Совет: временно убери image.tag, пока не заведётся.
    # У Bitnami теги обычно длинные (16.x.y-debian-..), а "16" может не существовать.
    # image:
    #   tag: "16"

    auth:
      username: dopdoc
      password: dopdoc
      database: dopdoc   # лучше чтобы дефолтная DB была твоя, а не "postgres"

    primary:
      persistence:
        enabled: true
        size: 5Gi
        storageClass: longhorn

      initdb:
        scripts:
          01-create-multiple-dbs.sql: |
            CREATE DATABASE auth_db;
            -- database "dopdoc" уже создастся через auth.database выше, но пусть будет ок,
            -- только имей в виду: если она уже есть, CREATE DATABASE упадёт.
            -- CREATE DATABASE dopdoc;
          02-auth-db.sql: |
            \connect auth_db

            BEGIN;

            CREATE TABLE users (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                email TEXT UNIQUE,
                password_hash TEXT NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT true,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                last_login_at TIMESTAMP
            );

            CREATE TABLE refresh_tokens (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                token_hash TEXT NOT NULL UNIQUE,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                expires_at TIMESTAMP NOT NULL,
                revoked_at TIMESTAMP,
                user_agent TEXT,
                ip INET,
                CONSTRAINT refresh_tokens_exp_chk CHECK (expires_at > created_at)
            );

            CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
            CREATE INDEX idx_refresh_tokens_user_created ON refresh_tokens(user_id, created_at DESC);
            CREATE INDEX idx_refresh_tokens_not_revoked ON refresh_tokens(user_id) WHERE revoked_at IS NULL;
            CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

            COMMIT;
