apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
  namespace: arc-system
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      sourceRef:
        kind: HelmRepository
        name: arc-oci
        namespace: arc-system
      # version: "0.x.x"  
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
