# clusters/k3s-home/infra/longhorn-helm.yml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
  metadata:
    name: longhorn
    namespace: longhorn-system
  spec:
    releaseName: longhorn
    interval: 30m
    chart:
      spec:
        chart: longhorn
        version: "1.10.0"
        sourceRef:
          kind: HelmRepository
          name: longhorn
          namespace: flux-system
    install:
      createNamespace: false
    upgrade:
      remediation:
        retries: 3
