apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: qdrant
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: qdrant
        namespace: flux-system
  targetNamespace: qdrant
  install:
    createNamespace: true
  values:
    replicaCount: 1
    service:
      type: ClusterIP
      ports:
        http: 6333
        grpc: 6334
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      storageClassName: longhorn
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 750m
        memory: 2Gi


